<a href="https://colab.research.google.com/github/PavanPabolu/AIML-Python/blob/main/Py_10_minutes_to_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reference:

10 minutes to pandas
https://pandas.pydata.org/docs/user_guide/10min.html

In [ ]:
In [1]: import numpy as np

In [2]: import pandas as pd

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [ ]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
dates = pd.date_range("20130101", periods=6)

In [ ]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [ ]:
df

                   A         B         C         D
2013-01-01  0.518025 -1.645245  0.477574 -1.095506
2013-01-02 -0.329181  0.466333  0.914975  1.325265
2013-01-03  1.062794  0.398845 -0.362521  1.012214
2013-01-04 -0.501268  0.666554 -0.798587  0.270128
2013-01-05 -1.157770 -0.038667 -0.548138  0.323350
2013-01-06  1.360229 -0.156158 -0.815710  0.455759

In [ ]:
list1 = list("ABCDEF")

In [ ]:
list1

['A', 'B', 'C', 'D', 'E', 'F']